In [2]:
import numpy as np
import random
b = np.array([[[1,2,3,4],[1,3,4,5]],[[2,4,7,5],[8,4,3,5]],[[2,5,7,3],[1,5,3,7]]]);
# print("before:\n",b,"\nend");
c=np.sort(b,axis=1);
rg=np.eye(3,6,0,dtype=np.int)
a=np.arange(16).reshape(4,4)
s=np.linalg.norm(b,axis=1);

print(a*np.pi)
print(random.random())
print(np.sqrt(10))
training_data = [("the wall street journal reported today that apple corporation made money".split(),
                    "B I I I O O O B I O O".split()),
                    ("georgia tech is a university in georgia".split(), "B I O O O O B".split())]
print(training_data)

[[ 0.          3.14159265  6.28318531  9.42477796]
 [12.56637061 15.70796327 18.84955592 21.99114858]
 [25.13274123 28.27433388 31.41592654 34.55751919]
 [37.69911184 40.8407045  43.98229715 47.1238898 ]]
0.3601972407718368
3.1622776601683795
[(['the', 'wall', 'street', 'journal', 'reported', 'today', 'that', 'apple', 'corporation', 'made', 'money'], ['B', 'I', 'I', 'I', 'O', 'O', 'O', 'B', 'I', 'O', 'O']), (['georgia', 'tech', 'is', 'a', 'university', 'in', 'georgia'], ['B', 'I', 'O', 'O', 'O', 'O', 'B'])]
